package ArduinoML.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Action = 0;
  public static final int Actuator = 1;
  public static final int ActuatorReference = 2;
  public static final int App = 3;
  public static final int Brick = 4;
  public static final int Sensor = 5;
  public static final int SensorReference = 6;
  public static final int SignalTransition = 7;
  public static final int State = 8;
  public static final int StateReference = 9;
  public static final int TimeTransition = 10;
  public static final int Transition = 11;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xebc7d5848dc64f91L, 0xa9e8fcd9cb7722d1L);
    builder.put(0x5e58140c4c4bbd6fL, Action);
    builder.put(0x5e58140c4c4bbd78L, Actuator);
    builder.put(0x5b843678b15b80edL, ActuatorReference);
    builder.put(0x5e58140c4c4bbd5fL, App);
    builder.put(0x5e58140c4c4bbd9aL, Brick);
    builder.put(0x5e58140c4c4bbdedL, Sensor);
    builder.put(0x5b843678b158f8d7L, SensorReference);
    builder.put(0x5e58140c4c4bbdf6L, SignalTransition);
    builder.put(0x5e58140c4c4bbd67L, State);
    builder.put(0x5b843678b158f914L, StateReference);
    builder.put(0x5e58140c4c4bbdf9L, TimeTransition);
    builder.put(0x5b843678b17ad845L, Transition);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
